@bareUrl = http://localhost:3000/api
@resourceName=products


# @name getAll
GET {{bareUrl}}/{{resourceName}}
###

# @name addNew
POST {{bareUrl}}/{{resourceName}}
Content-Type: application/json; charset=utf-8
{
   "categoryId": 1,
   "name": "new product",
   "desc": "ldsaafs",
   "color": "mint green",
   "price": 559,
   "thumbnailUrl": "http://placeimg.com/400/400"
}
###

# @name update
PATCH   {{bareUrl}}/{{resourceName}}/11
Content-Type: application/json; charset=utf-8
{
   "name": "Update new category"
}
###

# @name remove
DELETE {{bareUrl}}/{{resourceName}}/11
###